language: go
go:
  - 1.13.5
env:
  global:
    - SHA512_CMD=sha512sum
    - GO111MODULE=on
matrix:
  include:
  - os: linux
    dist: bionic
  - os: osx
    env: SHA512_CMD="shasum -a 512"
  - os: windows
addons:
  sonarcloud:
    organization: 030-github
    token:
      secure: $SONAR_TOKEN
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.21.0 golangci-lint run -v; fi
  - export DELIVERABLE="bcbsn-${TRAVIS_OS_NAME}"
  - go test -short -cover -v -coverprofile=coverage.out -covermode=atomic ./...
  - go build -o $DELIVERABLE
  - $SHA512_CMD $DELIVERABLE > ${DELIVERABLE}.sha512.txt
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then sonar-scanner -Dsonar.projectKey=030_bcbsn -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.exclusions=**/*_test.go -Dsonar.go.coverage.reportPaths="coverage.out"; fi
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - $DELIVERABLE
    - ${DELIVERABLE}.sha512.txt
  skip_cleanup: true
  on:
    tags: true
