language: go
go:
  - 1.12.1
env:
  - GIMME_OS=linux
  - GIMME_OS=darwin
  - GIMME_OS=windows
script:
  - diff -u <(echo -n) <(gofmt -d ./)
  - export DELIVERABLE="golang-bitbucket-cloud-build-status-notifier-${GIMME_OS}"
  - go test -short -cover -v -coverprofile=coverage.out -covermode=atomic ./...
  - GOARCH=amd64 go build -o $DELIVERABLE
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - ${DELIVERABLE}
    - ${DELIVERABLE}.sha512.txt
  skip_cleanup: true
  on:
    tags: true
