language: go
script:
  - export DELIVERABLE=golang-bitbucket-cloud-build-status-notifier
  - wget https://gist.githubusercontent.com/030/9a74cf6537b32dfa666cdcbd9c0ccac7/raw/8bb274a19204a0ab2a1dff0e0ec28482dd7745d0/go-releases.sh
  - chmod +x ./go-releases.sh
  - ./go-releases.sh $DELIVERABLE
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - ${DELIVERABLE}-darwin
    - ${DELIVERABLE}-darwin.sha512.txt
    - ${DELIVERABLE}-linux
    - ${DELIVERABLE}-linux.sha512.txt
    - ${DELIVERABLE}-windows.exe
    - ${DELIVERABLE}-windows.exe.sha512.txt
  skip_cleanup: true
  on:
    tags: true