---
name: Docker
'on':
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: utrecht/bcbsn:${{ steps.version.outputs.version }}
          build-args: |
            VERSION=${{ github.ref }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
