---
name: Hadolint
'on': push
jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image using hadolint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
